GET http://localhost:3000/api/inmueble


####
POST http://localhost:3000/api/inmueble
Content-Type: application/json

{
  "floor": 8,
  "letter": "F",
  "extension": 800,
  "number_rooms": 6,
  "rented": false,
  "owners_name": "Mario",
  "contact_email": "mario@gmail.com"
}

###
PUT http://localhost:3000/api/inmueble/646549cf4c1c1b6e49e00cf8
Content-Type: application/json

{
"rented": true
}


####
DELETE http://localhost:3000/api/inmueble/646549cf4c1c1b6e49e00cf8