GET http://localhost:3000/api/inmueble


####
POST http://localhost:3000/api/inmueble
Content-Type: application/json

{
    "floor": 8,
  "letter": "F",
  "extension": 1200,
  "number_rooms": 6,
  "rented": false,
  "owners_name": "Mario",
  "contact_email": "mario@gmail.com"
}

###
PUT http://localhost:3000/api/inmueble/12


####
DELETE http://localhost:3000/api/inmueble/123